2.Family connection

Roditel'      = frozenset({'anim', 'masc', 'NOUN', 'sing'})
Otec          = frozenset({'anim', 'masc', 'NOUN', 'sing'})
Tyotka        = frozenset({'anim', 'femn', 'NOUN', 'sing'})
Plemyannik    = frozenset({'anim', 'masc', 'NOUN', 'sing'})
Gena          = frozenset({'anim', 'femn', 'NOUN', 'sing'})
Cum           = frozenset({'anim', 'masc', 'NOUN', 'sing'})
Svat	      = frozenset({'anim', 'masc', 'NOUN', 'sing'})
Sem'ya        = frozenset({'inan', 'femn', 'NOUN', 'sing'})
Supruga       = frozenset({'anim', 'femn', 'NOUN', 'sing'})
Rodstvennitsa = frozenset({'anim', 'femn', 'NOUN', 'sing'})
Muzh 	      = frozenset({'anim', 'masc', 'NOUN', 'sing'})
Lyubovnica    = frozenset({'anim', 'femn', 'NOUN', 'sing'})
Syn	      = frozenset({'anim', 'masc', 'NOUN', 'sing'})
Mat'	      = frozenset({'anim', 'femn', 'NOUN', 'sing'})
Dyadya 	      = frozenset({'anim', 'masc', 'NOUN', 'sing'})
Naslednik     = frozenset({'anim', 'masc', 'NOUN', 'sing'})
Sestra 	      = frozenset({'anim', 'femn', 'NOUN', 'sing'})
Babushka      = frozenset({'anim', 'femn', 'NOUN', 'sing'})
Brat          = frozenset({'anim', 'masc', 'NOUN', 'sing'})
Rodstvennik   = frozenset({'anim', 'masc', 'NOUN', 'sing'})
Plemyannitsa  = frozenset({'anim', 'femn', 'NOUN', 'sing'})
Tyotya 	      = frozenset({'anim', 'femn', 'NOUN', 'sing'})
Drug	      = frozenset({'anim', 'masc', 'NOUN', 'sing'})
Priyatel'     = frozenset({'anim', 'masc', 'NOUN', 'sing'})
Vdova         = frozenset({'anim', 'femn', 'NOUN', 'sing'})