3.Профессиональные связи

Avtor        	 = frozenset({'anim', 'masc', 'NOUN', 'sing'})
Administrator 	 = frozenset({'anim', 'masc', 'NOUN', 'sing'})
Aktyor        	 = frozenset({'anim', 'masc', 'NOUN', 'sing'})
Alkhimik     	 = frozenset({'anim', 'masc', 'NOUN', 'sing'})
Al'pinist    	 = frozenset({'anim', 'masc', 'NOUN', 'sing'})
Arkhierej    	 = frozenset({'anim', 'masc', 'NOUN', 'sing'})
Artist       	 = frozenset({'anim', 'masc', 'NOUN', 'sing'})
Artistka      	 = frozenset({'anim', 'femn', 'NOUN', 'sing'})
Astrolog      	 = frozenset({'anim', 'masc', 'NOUN', 'sing'})

Baron        	 = frozenset({'anim', 'masc', 'NOUN', 'sing'})
Baryshnik     	 = frozenset({'anim', 'masc', 'NOUN', 'sing'})
Belletrist    	 = frozenset({'anim', 'masc', 'NOUN', 'sing'})
Bogomolec    	 = frozenset({'anim', 'masc', 'NOUN', 'sing'})
Bukhgalter   	 = frozenset({'anim', 'masc', 'NOUN', 'sing'})
Bufetchik    	 = frozenset({'anim', 'masc', 'NOUN', 'sing'})

Vagonovozhataya  = frozenset({'anim', 'femn', 'NOUN', 'sing', 'Sgtm'})
Valyutchik       = frozenset({'anim', 'masc', 'NOUN', 'sing'})
Vedushchiy       = frozenset({'Subx', 'masc', 'ADJF', 'sing'})
Vrach 	         = frozenset({'anim', 'masc', 'NOUN', 'sing'})

Gaer		 = frozenset({'anim', 'masc', 'NOUN', 'sing'})
Gastrolyor	 = frozenset({'anim', 'masc', 'NOUN', 'sing'})
Gertsog		 = frozenset({'anim', 'masc', 'NOUN', 'sing'})
Glashatai        = frozenset({'anim', 'masc', 'NOUN', 'sing'})
Gornichnaya      = frozenset({'anim', 'femn', 'NOUN', 'sing'})
Gosudar' 	 = frozenset({'anim', 'masc', 'NOUN', 'sing'})
Grimyor 	 = frozenset({'anim', 'masc', 'NOUN', 'sing'})

Direktor	 = frozenset({'anim', 'masc', 'NOUN', 'sing'})
Dirizhor 	 = frozenset({'anim', 'masc', 'NOUN', 'sing'})
Doktor		 = frozenset({'anim', 'masc', 'NOUN', 'sing'})
Domovladelitsa 	 = frozenset({'anim', 'femn', 'NOUN', 'sing'})
Donna 		 = frozenset({'anim', 'femn', 'NOUN', 'sing'})
Dramaturg 	 = frozenset({'anim', 'masc', 'NOUN', 'sing'}) 

Zhurnalist	 = frozenset({'anim', 'masc', 'NOUN', 'sing'})
Zaveduyushchiy	 = frozenset({'Subx', 'masc', 'PRTF', 'sing', 'actv', 'impf', 'pres', 'intr'})
Zastroyshchik    = frozenset({'anim', 'masc', 'NOUN', 'sing'}) 
Zvezdochot 	 = frozenset({'anim', 'masc', 'NOUN', 'sing'}) 

Imperator	 = frozenset({'anim', 'masc', 'NOUN', 'sing'}) 
Inzhener 	 = frozenset({'anim', 'masc', 'NOUN', 'sing'}) 
Istorik 	 = frozenset({'anim', 'masc', 'NOUN', 'sing'}) 

Kalif 		 = frozenset({'anim', 'masc', 'NOUN', 'sing', 'Name'}) 
Kameristka       = frozenset({'anim', 'femn', 'NOUN', 'sing'})
Kapel'diner	 = frozenset({'anim', 'masc', 'NOUN', 'sing'}) 
Kassirsha 	 = frozenset({'anim', 'femn', 'NOUN', 'sing'})
Kesar' 		 = frozenset({'anim', 'masc', 'NOUN', 'sing'}) 
Knyaz'		 = frozenset({'anim', 'masc', 'NOUN', 'sing'}) 
Korol'		 = frozenset({'anim', 'masc', 'NOUN', 'sing'}) 
Koroleva	 = frozenset({'anim', 'femn', 'NOUN', 'sing'})
Kompozitor	 = frozenset({'anim', 'masc', 'NOUN', 'sing'}) 
Komsomolka 	 = frozenset({'anim', 'femn', 'NOUN', 'sing'})
Konduktor 	 = frozenset({'anim', 'masc', 'NOUN', 'sing'}) 
Konovod 	 = frozenset({'anim', 'masc', 'NOUN', 'sing'}) 
Konsul'tant 	 = frozenset({'anim', 'masc', 'NOUN', 'sing'}) 
Kontramarochnik  = frozenset({'anim', 'masc', 'NOUN', 'sing'}) 
Konferans'e 	 = frozenset({'anim', 'masc', 'NOUN', 'sing', 'Fixd'}) 
Konʹkobezhets 	 = frozenset({'anim', 'masc', 'NOUN', 'sing'})  
Kritik 		 = frozenset({'anim', 'masc', 'NOUN', 'sing'})
Kur'yer 	 = frozenset({'anim', 'masc', 'NOUN', 'sing'}) 
Kur'yerskiy 	 = frozenset({'masc', 'ADJF', 'sing'}) 
Kur'yersha	 = frozenset({'anim', 'femn', 'NOUN', 'sing'})
Kuharka 	 = frozenset({'anim', 'femn', 'NOUN', 'sing'})

Landskneht 	 = frozenset({'anim', 'masc', 'NOUN', 'sing'}) 
Liehat		 = frozenset({'anim', 'masc', 'NOUN', 'sing'}) 
Literator 	 = frozenset({'anim', 'masc', 'NOUN', 'sing'}) 

Mag		 = frozenset({'anim', 'masc', 'NOUN', 'sing'}) 
Manipul 	 = frozenset({'inan', 'masc', 'NOUN', 'sing'}) 
Markitantka 	 = frozenset({'anim', 'femn', 'NOUN', 'sing'})
Markiza 	 = frozenset({'anim', 'femn', 'NOUN', 'sing'})
Master 		 = frozenset({'anim', 'masc', 'NOUN', 'sing'})
Mashinistka	 = frozenset({'anim', 'femn', 'NOUN', 'sing'})
Maestro 	 = frozenset({'anim', 'masc', 'NOUN', 'sing', 'Fixd'}) 
Militsioner	 = frozenset({'anim', 'masc', 'NOUN', 'sing'})
Muzykant 	 = frozenset({'anim', 'masc', 'NOUN', 'sing'}) 

Nachal'nik 	 = frozenset({'anim', 'masc', 'NOUN', 'sing'}) 
Nevropatolog	 = frozenset({'anim', 'masc', 'NOUN', 'sing'}) 
Novellist	 = frozenset({'anim', 'masc', 'NOUN', 'sing'}) 
Nyan'ka   	 = frozenset({'anim', 'femn', 'NOUN', 'sing'})
Nyanya 		 = frozenset({'anim', 'femn', 'NOUN', 'sing'})

Ordinarec 	 = frozenset({'anim', 'masc', 'NOUN', 'sing'})
Ofitser 	 = frozenset({'anim', 'masc', 'NOUN', 'sing'})
Ofitsiant 	 = frozenset({'anim', 'masc', 'NOUN', 'sing'})

Palach 		 = frozenset({'anim', 'masc', 'NOUN', 'sing'})
Patologoanatom 	 = frozenset({'anim', 'masc', 'NOUN', 'sing'})
Pervosvyashchennik = frozenset({'anim', 'masc', 'NOUN', 'sing'})
Perevodchik 	 = frozenset({'anim', 'masc', 'NOUN', 'sing'})
Pirat 		 = frozenset({'anim', 'masc', 'NOUN', 'sing'})
Pisatel'  	 = frozenset({'anim', 'masc', 'NOUN', 'sing'})
Planovik 	 = frozenset({'anim', 'masc', 'NOUN', 'sing'})
Povar 		 = frozenset({'anim', 'masc', 'NOUN', 'sing'})
Povaryonok 	 = frozenset({'anim', 'masc', 'NOUN', 'sing'})
Povelytelʹnytsa  = frozenset({'anim', 'femn', 'NOUN', 'sing'})
Pozharnyy 	 = frozenset({'anim', 'masc', 'NOUN', 'sing'})
Pomoshchnik 	 = frozenset({'anim', 'masc', 'NOUN', 'sing'})
Portnykha 	 = frozenset({'anim', 'femn', 'NOUN', 'sing'})
Pochtal'on 	 = frozenset({'anim', 'masc', 'NOUN', 'sing'})
Poet 	 	 = frozenset({'anim', 'masc', 'NOUN', 'sing'})
Predsedatel'	 = frozenset({'anim', 'masc', 'NOUN', 'sing'})
Predskazatel'	 = frozenset({'anim', 'masc', 'NOUN', 'sing'})
Predstavitel' 	 = frozenset({'anim', 'masc', 'NOUN', 'sing'}) 
Prezident 	 = frozenset({'anim', 'masc', 'NOUN', 'sing'})
Pryvat-dotsent 	 = frozenset({'anim', 'masc', 'NOUN', 'sing'})
Provodnik 	 = frozenset({'anim', 'masc', 'NOUN', 'sing'}) 
Prodavets 	 = frozenset({'anim', 'masc', 'NOUN', 'sing'})
Prodavshchitsa 	 = frozenset({'anim', 'femn', 'NOUN', 'sing'})
Prozektor	 = frozenset({'anim', 'masc', 'NOUN', 'sing'})
Prokurator 	 = frozenset({'anim', 'masc', 'NOUN', 'sing'})
Professor	 = frozenset({'anim', 'masc', 'NOUN', 'sing'})
Psikhiatr 	 = frozenset({'anim', 'masc', 'NOUN', 'sing'}) 
Puteshestvennik  = frozenset({'anim', 'masc', 'NOUN', 'sing'}) 

Rab		 = frozenset({'anim', 'masc', 'NOUN', 'sing'}) 
Rabotnitsa       = frozenset({'anim', 'femn', 'NOUN', 'sing'})
Rasskazchik 	 = frozenset({'anim', 'masc', 'NOUN', 'sing'}) 
Regent		 = frozenset({'anim', 'masc', 'NOUN', 'sing'})  
Redaktor 	 = frozenset({'anim', 'masc', 'NOUN', 'sing'})

Sborshchik 	 = frozenset({'anim', 'masc', 'NOUN', 'sing'})
Svyashchennik 	 = frozenset({'anim', 'masc', 'NOUN', 'sing'})  
Sekretar' 	 = frozenset({'anim', 'masc', 'NOUN', 'sing'})  
Sledovatel' 	 = frozenset({'anim', 'masc', 'NOUN', 'sing'})  
Sluga 		 = frozenset({'anim', 'masc', 'NOUN', 'sing'})  
Sluzhashchiy	 = frozenset({'Subx', 'masc', 'PRTF', 'sing', 'actv', 'impf', 'pres', 'tran'})
Soldat 	   	 = frozenset({'anim', 'masc', 'NOUN', 'sing'})  
Spetsialist	 = frozenset({'anim', 'masc', 'NOUN', 'sing'})
Sotrudnik 	 = frozenset({'anim', 'masc', 'NOUN', 'sing'}) 
Scenarist 	 = frozenset({'anim', 'masc', 'NOUN', 'sing'})  
Schetovod 	 = frozenset({'anim', 'masc', 'NOUN', 'sing'}) 
Syshchik 	 = frozenset({'anim', 'masc', 'NOUN', 'sing'}) 

Tyetrarkh 	 = frozenset({'anim', 'masc', 'NOUN', 'sing'}) 
Tekhnik		 = frozenset({'anim', 'masc', 'NOUN', 'sing'}) 
Tochil'shchik 	 = frozenset({'anim', 'masc', 'NOUN', 'sing'}) 
Turist 		 = frozenset({'anim', 'masc', 'NOUN', 'sing'}) 
Tyuremshchik 	 = frozenset({'anim', 'masc', 'NOUN', 'sing'})  

Uborshchitsa	 = frozenset({'anim', 'femn', 'NOUN', 'sing'})
Uchenik 	 = frozenset({'anim', 'masc', 'NOUN', 'sing'})
Uchyonyj	 = frozenset({'anim', 'masc', 'NOUN', 'sing'}) 

Falʹshyvomonetchyk = frozenset({'anim', 'masc', 'NOUN', 'sing'}) 
Fel'dsheritsa 	 = frozenset({'anim', 'femn', 'NOUN', 'sing'})
Filosof 	 = frozenset({'anim', 'masc', 'NOUN', 'sing'}) 
Findirektor 	 = frozenset({'anim', 'masc', 'NOUN', 'sing'}) 
Fokusnik 	 = frozenset({'anim', 'masc', 'NOUN', 'sing'}) 

Khirurg		 = frozenset({'anim', 'masc', 'NOUN', 'sing'})
Khozyain	 = frozenset({'anim', 'masc', 'NOUN', 'sing'}) 
Khozyayka 	 = frozenset({'anim', 'femn', 'NOUN', 'sing'})
Khorist 	 = frozenset({'anim', 'masc', 'NOUN', 'sing'}) 
Khormeyster	 = frozenset({'anim', 'masc', 'NOUN', 'sing'}) 
Khronikor 	 = frozenset({'anim', 'masc', 'NOUN', 'sing'}) 

Сharodey	 = frozenset({'anim', 'masc', 'NOUN', 'sing'}) 

Shvyeitsar 	 = frozenset({'anim', 'masc', 'NOUN', 'sing'}) 
Shef 		 = frozenset({'anim', 'masc', 'NOUN', 'sing'}) 
Shofyor 	 = frozenset({'anim', 'masc', 'NOUN', 'sing'}) 
Shuler 		 = frozenset({'anim', 'masc', 'NOUN', 'sing'})  

Ekonomist 	 = frozenset({'anim', 'masc', 'NOUN', 'sing'})  

Yuvelir 	 = frozenset({'anim', 'masc', 'NOUN', 'sing'})  



